URLs:
  - url: https://api.apis.guru/v2/list.json
    name: guru
  - url: https://api.publicapis.org/entries
    name: piblicapis
  - url : https://api.artic.edu/api/v1/artworks/search?q=cats
    name: artic
  - url : https://api.artic.edu/api/v10/artworks/search?q=cats
    name: fake
Interval_s: 3